window.APP_DATA = {
  "meta": {
    "title": "小程序数据驾驶舱",
    "dailySheet": "06.12",
    "dailyPeriod": {
      "baseline": "6月5日",
      "current": "今日"
    },
    "weeklyPeriod": {
      "baseline": "6月1日-6月7日",
      "current": "6月8日-6月14日"
    },
    "sourceFiles": [
      "6月份小程序每日.xlsx",
      "6月份小程序每人品牌数据(周环比).xlsx"
    ],
    "dailyRowCount": 95,
    "weeklyRowCount": 82
  },
  "dailyRows": [
    {
      "id": "daily-1",
      "name": "酷二狗电竞俱乐部",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 1462,
      "uvToday": 1076,
      "consultPrev": 33,
      "consultToday": 24,
      "ordersPrev": 61,
      "ordersToday": 66,
      "newPrev": 13,
      "newToday": 8,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-2",
      "name": "吞天电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 410,
      "uvToday": 196,
      "consultPrev": 56,
      "consultToday": 26,
      "ordersPrev": 38,
      "ordersToday": 25,
      "newPrev": 7,
      "newToday": 12,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-3",
      "name": "EGM背心电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 795,
      "uvToday": 426,
      "consultPrev": 10,
      "consultToday": 14,
      "ordersPrev": 8,
      "ordersToday": 9,
      "newPrev": 3,
      "newToday": 5,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-4",
      "name": "追核电竞园区",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 536,
      "uvToday": 566,
      "consultPrev": 25,
      "consultToday": 38,
      "ordersPrev": 20,
      "ordersToday": 23,
      "newPrev": 10,
      "newToday": 9,
      "brushCount": 300,
      "note": ""
    },
    {
      "id": "daily-5",
      "name": "东东电竞点单",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 1491,
      "uvToday": 1577,
      "consultPrev": 139,
      "consultToday": 154,
      "ordersPrev": 66,
      "ordersToday": 74,
      "newPrev": 32,
      "newToday": 35,
      "brushCount": 300,
      "note": ""
    },
    {
      "id": "daily-6",
      "name": "皇帝电竞官号",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 1021,
      "uvToday": 933,
      "consultPrev": 142,
      "consultToday": 133,
      "ordersPrev": 79,
      "ordersToday": 57,
      "newPrev": 28,
      "newToday": 17,
      "brushCount": 300,
      "note": ""
    },
    {
      "id": "daily-7",
      "name": "宁州电竞",
      "owner": "CP",
      "status": "申诉中",
      "uvPrev": 0,
      "uvToday": 0,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-8",
      "name": "A7电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 1151,
      "uvToday": 1011,
      "consultPrev": 31,
      "consultToday": 21,
      "ordersPrev": 3,
      "ordersToday": 14,
      "newPrev": 3,
      "newToday": 6,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-9",
      "name": "小河电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 151,
      "uvToday": 270,
      "consultPrev": 20,
      "consultToday": 31,
      "ordersPrev": 6,
      "ordersToday": 14,
      "newPrev": 3,
      "newToday": 13,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-10",
      "name": "得吃电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 341,
      "uvToday": 314,
      "consultPrev": 49,
      "consultToday": 57,
      "ordersPrev": 35,
      "ordersToday": 55,
      "newPrev": 17,
      "newToday": 21,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-11",
      "name": "星光电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 323,
      "uvToday": 280,
      "consultPrev": 25,
      "consultToday": 33,
      "ordersPrev": 25,
      "ordersToday": 19,
      "newPrev": 8,
      "newToday": 7,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-12",
      "name": "飞禾电竞",
      "owner": "CP",
      "status": "申诉中",
      "uvPrev": 84,
      "uvToday": 0,
      "consultPrev": 8,
      "consultToday": 0,
      "ordersPrev": 11,
      "ordersToday": 0,
      "newPrev": 2,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-13",
      "name": "张德帅电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 0,
      "uvToday": 38,
      "consultPrev": 0,
      "consultToday": 1,
      "ordersPrev": 0,
      "ordersToday": 1,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-14",
      "name": "颗秒电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 379,
      "uvToday": 279,
      "consultPrev": 7,
      "consultToday": 10,
      "ordersPrev": 10,
      "ordersToday": 14,
      "newPrev": 2,
      "newToday": 1,
      "brushCount": 300,
      "note": ""
    },
    {
      "id": "daily-15",
      "name": "落川电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 687,
      "uvToday": 896,
      "consultPrev": 97,
      "consultToday": 64,
      "ordersPrev": 100,
      "ordersToday": 64,
      "newPrev": 38,
      "newToday": 22,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-16",
      "name": "明星电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 826,
      "uvToday": 580,
      "consultPrev": 29,
      "consultToday": 31,
      "ordersPrev": 27,
      "ordersToday": 26,
      "newPrev": 17,
      "newToday": 15,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-17",
      "name": "财神电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 442,
      "uvToday": 364,
      "consultPrev": 28,
      "consultToday": 25,
      "ordersPrev": 10,
      "ordersToday": 3,
      "newPrev": 4,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-18",
      "name": "零月电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 0,
      "uvToday": 0,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-19",
      "name": "白鲨电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 34,
      "uvToday": 365,
      "consultPrev": 4,
      "consultToday": 18,
      "ordersPrev": 4,
      "ordersToday": 8,
      "newPrev": 2,
      "newToday": 5,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-20",
      "name": "安安队",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 0,
      "uvToday": 0,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-21",
      "name": "莽盒电竞",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 47,
      "uvToday": 331,
      "consultPrev": 6,
      "consultToday": 8,
      "ordersPrev": 3,
      "ordersToday": 2,
      "newPrev": 2,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-22",
      "name": "汇总",
      "owner": "CP",
      "status": "正常",
      "uvPrev": 10180,
      "uvToday": 9502,
      "consultPrev": 709,
      "consultToday": 688,
      "ordersPrev": 506,
      "ordersToday": 474,
      "newPrev": 191,
      "newToday": 180,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-23",
      "name": "稳啦电竞点单",
      "owner": "在东",
      "status": "正常",
      "uvPrev": 799,
      "uvToday": 487,
      "consultPrev": 16,
      "consultToday": 8,
      "ordersPrev": 9,
      "ordersToday": 6,
      "newPrev": 5,
      "newToday": 1,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-24",
      "name": "天霸电子竞技陪玩店",
      "owner": "在东",
      "status": "正常",
      "uvPrev": 542,
      "uvToday": 627,
      "consultPrev": 76,
      "consultToday": 83,
      "ordersPrev": 50,
      "ordersToday": 65,
      "newPrev": 9,
      "newToday": 21,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-25",
      "name": "初心纯女电竞",
      "owner": "在东",
      "status": "正常",
      "uvPrev": 566,
      "uvToday": 736,
      "consultPrev": 48,
      "consultToday": 34,
      "ordersPrev": 26,
      "ordersToday": 18,
      "newPrev": 13,
      "newToday": 10,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-26",
      "name": "麦小龙电竞点单",
      "owner": "在东",
      "status": "正常",
      "uvPrev": 109,
      "uvToday": 293,
      "consultPrev": 7,
      "consultToday": 25,
      "ordersPrev": 6,
      "ordersToday": 6,
      "newPrev": 2,
      "newToday": 4,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-27",
      "name": "家长电竞",
      "owner": "在东",
      "status": "正常",
      "uvPrev": 181,
      "uvToday": 235,
      "consultPrev": 15,
      "consultToday": 14,
      "ordersPrev": 6,
      "ordersToday": 9,
      "newPrev": 1,
      "newToday": 3,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-28",
      "name": "老飞宇俱乐部点单",
      "owner": "在东",
      "status": "正常",
      "uvPrev": 124,
      "uvToday": 344,
      "consultPrev": 12,
      "consultToday": 21,
      "ordersPrev": 2,
      "ordersToday": 12,
      "newPrev": 1,
      "newToday": 6,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-29",
      "name": "老飞宇陪玩",
      "owner": "在东",
      "status": "正常",
      "uvPrev": 1354,
      "uvToday": 661,
      "consultPrev": 12,
      "consultToday": 13,
      "ordersPrev": 4,
      "ordersToday": 5,
      "newPrev": 4,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-30",
      "name": "战门电竞",
      "owner": "在东",
      "status": "申诉中",
      "uvPrev": 0,
      "uvToday": 30,
      "consultPrev": 0,
      "consultToday": 5,
      "ordersPrev": 0,
      "ordersToday": 1,
      "newPrev": 0,
      "newToday": 1,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-31",
      "name": "PeRo电竞护航店（原PeRo俱乐部护航）",
      "owner": "在东",
      "status": "申诉中",
      "uvPrev": 0,
      "uvToday": 0,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-32",
      "name": "立了电竞",
      "owner": "在东",
      "status": "申诉中",
      "uvPrev": 18,
      "uvToday": 12,
      "consultPrev": 2,
      "consultToday": 1,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-33",
      "name": "keg电竞官号",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 279,
      "uvToday": 1218,
      "consultPrev": 2,
      "consultToday": 6,
      "ordersPrev": 2,
      "ordersToday": 14,
      "newPrev": 2,
      "newToday": 4,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-34",
      "name": "鼠鼠电竞护航点单（新）",
      "owner": "子潇",
      "status": "封禁中",
      "uvPrev": 119,
      "uvToday": 135,
      "consultPrev": 6,
      "consultToday": 17,
      "ordersPrev": 1,
      "ordersToday": 5,
      "newPrev": 0,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-35",
      "name": "（L类）牛马八宝粥电竞点单",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 1342,
      "uvToday": 1161,
      "consultPrev": 136,
      "consultToday": 90,
      "ordersPrev": 109,
      "ordersToday": 83,
      "newPrev": 36,
      "newToday": 32,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-36",
      "name": "（L类）龙昊电竞俱乐部",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 825,
      "uvToday": 332,
      "consultPrev": 8,
      "consultToday": 7,
      "ordersPrev": 8,
      "ordersToday": 9,
      "newPrev": 4,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-37",
      "name": "（L类）红狗电竞",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 60,
      "uvToday": 55,
      "consultPrev": 3,
      "consultToday": 6,
      "ordersPrev": 6,
      "ordersToday": 6,
      "newPrev": 3,
      "newToday": 1,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-38",
      "name": "（L类）有米电竞点单（旧）",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 782,
      "uvToday": 697,
      "consultPrev": 81,
      "consultToday": 59,
      "ordersPrev": 72,
      "ordersToday": 61,
      "newPrev": 32,
      "newToday": 10,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-39",
      "name": "（L类）玩偶电竞点单",
      "owner": "子潇",
      "status": "封禁中",
      "uvPrev": 782,
      "uvToday": 1889,
      "consultPrev": 279,
      "consultToday": 328,
      "ordersPrev": 142,
      "ordersToday": 155,
      "newPrev": 70,
      "newToday": 77,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-40",
      "name": "赫晨电竞",
      "owner": "子潇",
      "status": "封禁中",
      "uvPrev": 219,
      "uvToday": 739,
      "consultPrev": 18,
      "consultToday": 18,
      "ordersPrev": 10,
      "ordersToday": 12,
      "newPrev": 5,
      "newToday": 3,
      "brushCount": 300,
      "note": ""
    },
    {
      "id": "daily-41",
      "name": "（L类）H4电竞俱乐部",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 359,
      "uvToday": 360,
      "consultPrev": 35,
      "consultToday": 49,
      "ordersPrev": 31,
      "ordersToday": 441,
      "newPrev": 11,
      "newToday": 11,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-42",
      "name": "新光电竞",
      "owner": "子潇",
      "status": "封禁中",
      "uvPrev": 395,
      "uvToday": 263,
      "consultPrev": 37,
      "consultToday": 25,
      "ordersPrev": 17,
      "ordersToday": 22,
      "newPrev": 8,
      "newToday": 8,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-43",
      "name": "（L类）鹤仙电竞",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 202,
      "uvToday": 167,
      "consultPrev": 25,
      "consultToday": 11,
      "ordersPrev": 23,
      "ordersToday": 12,
      "newPrev": 6,
      "newToday": 4,
      "brushCount": 300,
      "note": ""
    },
    {
      "id": "daily-44",
      "name": "（L类）俭条电竞",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 903,
      "uvToday": 890,
      "consultPrev": 16,
      "consultToday": 32,
      "ordersPrev": 12,
      "ordersToday": 35,
      "newPrev": 7,
      "newToday": 19,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-45",
      "name": "（L类）凛冬俱乐部",
      "owner": "子潇",
      "status": "封禁中",
      "uvPrev": 452,
      "uvToday": 1033,
      "consultPrev": 45,
      "consultToday": 98,
      "ordersPrev": 19,
      "ordersToday": 50,
      "newPrev": 10,
      "newToday": 38,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-46",
      "name": "（L类）天帝俱乐部",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 978,
      "uvToday": 957,
      "consultPrev": 71,
      "consultToday": 68,
      "ordersPrev": 35,
      "ordersToday": 34,
      "newPrev": 20,
      "newToday": 23,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-47",
      "name": "（L类）财阀俱乐部",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 83,
      "uvToday": 355,
      "consultPrev": 12,
      "consultToday": 45,
      "ordersPrev": 2,
      "ordersToday": 28,
      "newPrev": 1,
      "newToday": 22,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-48",
      "name": "（L类）冰刃俱乐部",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 290,
      "uvToday": 33,
      "consultPrev": 1,
      "consultToday": 0,
      "ordersPrev": 1,
      "ordersToday": 1,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-49",
      "name": "一甲电竞",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 22,
      "uvToday": 261,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-50",
      "name": "怪兽电竞丨(wx88c53f068b624385)",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 2153,
      "uvToday": 2271,
      "consultPrev": 298,
      "consultToday": 246,
      "ordersPrev": 179,
      "ordersToday": 199,
      "newPrev": 99,
      "newToday": 93,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-51",
      "name": "大自然电竞",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 496,
      "uvToday": 496,
      "consultPrev": 30,
      "consultToday": 50,
      "ordersPrev": 19,
      "ordersToday": 28,
      "newPrev": 14,
      "newToday": 22,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-52",
      "name": "闹特电竞",
      "owner": "子潇",
      "status": "封禁中",
      "uvPrev": 312,
      "uvToday": 158,
      "consultPrev": 9,
      "consultToday": 22,
      "ordersPrev": 5,
      "ordersToday": 9,
      "newPrev": 5,
      "newToday": 8,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-53",
      "name": "追风电竞",
      "owner": "子潇",
      "status": "正常",
      "uvPrev": 328,
      "uvToday": 80,
      "consultPrev": 11,
      "consultToday": 7,
      "ordersPrev": 6,
      "ordersToday": 3,
      "newPrev": 5,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-54",
      "name": "宝宝电竞",
      "owner": "子潇",
      "status": "封禁中",
      "uvPrev": 0,
      "uvToday": 59,
      "consultPrev": 0,
      "consultToday": 1,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-55",
      "name": "花来商行",
      "owner": "林诗羽√",
      "status": "正常",
      "uvPrev": 466,
      "uvToday": 557,
      "consultPrev": 0,
      "consultToday": 1,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-56",
      "name": "长官商行",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 1690,
      "uvToday": 1838,
      "consultPrev": 1,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-57",
      "name": "叮当商行",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 490,
      "uvToday": 507,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-58",
      "name": "厨神商行",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 732,
      "uvToday": 276,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 1,
      "ordersToday": 0,
      "newPrev": 1,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-59",
      "name": "H8商行",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 88,
      "uvToday": 139,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-60",
      "name": "牛马号商",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 222,
      "uvToday": 405,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-61",
      "name": "小炬商行",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 187,
      "uvToday": 168,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-62",
      "name": "大兵商行",
      "owner": "林诗羽",
      "status": "刚上新",
      "uvPrev": 0,
      "uvToday": 351,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-63",
      "name": "财神商行",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 390,
      "uvToday": 198,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-64",
      "name": "猩球电竞俱乐部陪玩",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 785,
      "uvToday": 362,
      "consultPrev": 20,
      "consultToday": 35,
      "ordersPrev": 7,
      "ordersToday": 12,
      "newPrev": 4,
      "newToday": 6,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-65",
      "name": "Kasa电竞",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 124,
      "uvToday": 139,
      "consultPrev": 21,
      "consultToday": 14,
      "ordersPrev": 9,
      "ordersToday": 8,
      "newPrev": 5,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-66",
      "name": "聆音女陪电竞",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 178,
      "uvToday": 408,
      "consultPrev": 2,
      "consultToday": 5,
      "ordersPrev": 1,
      "ordersToday": 2,
      "newPrev": 1,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-67",
      "name": "KEG电竞俱乐部点单",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 1525,
      "uvToday": 2357,
      "consultPrev": 10,
      "consultToday": 14,
      "ordersPrev": 5,
      "ordersToday": 8,
      "newPrev": 5,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-68",
      "name": "农场主电竞点单",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 77,
      "uvToday": 79,
      "consultPrev": 10,
      "consultToday": 2,
      "ordersPrev": 3,
      "ordersToday": 1,
      "newPrev": 3,
      "newToday": 1,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-69",
      "name": "农场主电竞三角洲",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 67,
      "uvToday": 193,
      "consultPrev": 3,
      "consultToday": 30,
      "ordersPrev": 0,
      "ordersToday": 5,
      "newPrev": 0,
      "newToday": 1,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-70",
      "name": "怪兽电竞俱乐部点单",
      "owner": "林诗羽",
      "status": "正常",
      "uvPrev": 0,
      "uvToday": 385,
      "consultPrev": 0,
      "consultToday": 6,
      "ordersPrev": 0,
      "ordersToday": 2,
      "newPrev": 0,
      "newToday": 1,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-71",
      "name": "茶哥电竞",
      "owner": "林诗羽",
      "status": "刚上新",
      "uvPrev": 0,
      "uvToday": 191,
      "consultPrev": 0,
      "consultToday": 7,
      "ordersPrev": 0,
      "ordersToday": 3,
      "newPrev": 0,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-72",
      "name": "星火电竞",
      "owner": "林诗羽",
      "status": "刚上新",
      "uvPrev": 0,
      "uvToday": 423,
      "consultPrev": 0,
      "consultToday": 17,
      "ordersPrev": 0,
      "ordersToday": 11,
      "newPrev": 0,
      "newToday": 7,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-73",
      "name": "求真电竞",
      "owner": "林诗羽",
      "status": "刚上新",
      "uvPrev": 0,
      "uvToday": 152,
      "consultPrev": 0,
      "consultToday": 21,
      "ordersPrev": 0,
      "ordersToday": 15,
      "newPrev": 0,
      "newToday": 10,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-74",
      "name": "（L类）二哈电竞点单",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 275,
      "uvToday": 215,
      "consultPrev": 23,
      "consultToday": 18,
      "ordersPrev": 6,
      "ordersToday": 5,
      "newPrev": 6,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-75",
      "name": "ENG俱乐部点单",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 362,
      "uvToday": 270,
      "consultPrev": 37,
      "consultToday": 43,
      "ordersPrev": 21,
      "ordersToday": 14,
      "newPrev": 9,
      "newToday": 3,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-76",
      "name": "HangHang电竞",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 80,
      "uvToday": 324,
      "consultPrev": 15,
      "consultToday": 13,
      "ordersPrev": 8,
      "ordersToday": 1,
      "newPrev": 4,
      "newToday": 0,
      "brushCount": 0,
      "note": "（去刷量）"
    },
    {
      "id": "daily-77",
      "name": "小炬电竞",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 374,
      "uvToday": 363,
      "consultPrev": 52,
      "consultToday": 36,
      "ordersPrev": 47,
      "ordersToday": 31,
      "newPrev": 7,
      "newToday": 7,
      "brushCount": 0,
      "note": "（去刷量）"
    },
    {
      "id": "daily-78",
      "name": "7JIA电子竞技点单",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 562,
      "uvToday": 224,
      "consultPrev": 11,
      "consultToday": 25,
      "ordersPrev": 5,
      "ordersToday": 19,
      "newPrev": 2,
      "newToday": 10,
      "brushCount": 0,
      "note": "（去刷量）"
    },
    {
      "id": "daily-79",
      "name": "乔乐电竞",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 0,
      "uvToday": 0,
      "consultPrev": 0,
      "consultToday": 0,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-80",
      "name": "老大电竞",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 829,
      "uvToday": 610,
      "consultPrev": 57,
      "consultToday": 35,
      "ordersPrev": 6,
      "ordersToday": 5,
      "newPrev": 5,
      "newToday": 3,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-81",
      "name": "打窝电竞",
      "owner": "贺祖丹",
      "status": "申诉中",
      "uvPrev": 58,
      "uvToday": 45,
      "consultPrev": 6,
      "consultToday": 1,
      "ordersPrev": 0,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-82",
      "name": "KEG电竞点单店",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 2492,
      "uvToday": 390,
      "consultPrev": 4,
      "consultToday": 3,
      "ordersPrev": 5,
      "ordersToday": 5,
      "newPrev": 3,
      "newToday": 3,
      "brushCount": 0,
      "note": "（去刷量）"
    },
    {
      "id": "daily-83",
      "name": "炮炮电竞店官号",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 75,
      "uvToday": 58,
      "consultPrev": 14,
      "consultToday": 11,
      "ordersPrev": 5,
      "ordersToday": 7,
      "newPrev": 1,
      "newToday": 1,
      "brushCount": 0,
      "note": "(去刷量）"
    },
    {
      "id": "daily-84",
      "name": "叮当电竞",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 168,
      "uvToday": 150,
      "consultPrev": 0,
      "consultToday": 32,
      "ordersPrev": 0,
      "ordersToday": 18,
      "newPrev": 0,
      "newToday": 13,
      "brushCount": 0,
      "note": "（去刷量）"
    },
    {
      "id": "daily-85",
      "name": "瓦瓦电竞",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 200,
      "uvToday": 405,
      "consultPrev": 31,
      "consultToday": 47,
      "ordersPrev": 7,
      "ordersToday": 6,
      "newPrev": 3,
      "newToday": 6,
      "brushCount": 0,
      "note": "（去刷量）"
    },
    {
      "id": "daily-86",
      "name": "海胆电竞点单",
      "owner": "贺祖丹",
      "status": "正常",
      "uvPrev": 567,
      "uvToday": 240,
      "consultPrev": 17,
      "consultToday": 14,
      "ordersPrev": 24,
      "ordersToday": 12,
      "newPrev": 9,
      "newToday": 2,
      "brushCount": 0,
      "note": "（去刷量）"
    },
    {
      "id": "daily-87",
      "name": "少羽的SY电竞护航",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 89,
      "uvToday": 300,
      "consultPrev": 4,
      "consultToday": 12,
      "ordersPrev": 1,
      "ordersToday": 7,
      "newPrev": 1,
      "newToday": 4,
      "brushCount": 350,
      "note": "（去刷量）"
    },
    {
      "id": "daily-88",
      "name": "粑粑电竞护航",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 177,
      "uvToday": 249,
      "consultPrev": 6,
      "consultToday": 15,
      "ordersPrev": 5,
      "ordersToday": 4,
      "newPrev": 1,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-89",
      "name": "Cs电竞护航",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 303,
      "uvToday": 48,
      "consultPrev": 7,
      "consultToday": 8,
      "ordersPrev": 6,
      "ordersToday": 4,
      "newPrev": 2,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-90",
      "name": "胜海电竞俱乐部",
      "owner": "谢宇茜",
      "status": "申诉中",
      "uvPrev": 253,
      "uvToday": 325,
      "consultPrev": 7,
      "consultToday": 19,
      "ordersPrev": 6,
      "ordersToday": 2,
      "newPrev": 1,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-91",
      "name": "拔牙电竞俱乐部",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 173,
      "uvToday": 106,
      "consultPrev": 10,
      "consultToday": 5,
      "ordersPrev": 6,
      "ordersToday": 0,
      "newPrev": 3,
      "newToday": 0,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-92",
      "name": "小里的电竞点单",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 133,
      "uvToday": 125,
      "consultPrev": 16,
      "consultToday": 18,
      "ordersPrev": 8,
      "ordersToday": 8,
      "newPrev": 3,
      "newToday": 3,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-93",
      "name": "带富电竞点单",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 55,
      "uvToday": 72,
      "consultPrev": 7,
      "consultToday": 5,
      "ordersPrev": 5,
      "ordersToday": 5,
      "newPrev": 3,
      "newToday": 2,
      "brushCount": 0,
      "note": ""
    },
    {
      "id": "daily-94",
      "name": "KEG电竞护航店",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 11,
      "uvToday": 400,
      "consultPrev": 0,
      "consultToday": 22,
      "ordersPrev": 3,
      "ordersToday": 81,
      "newPrev": 1,
      "newToday": 40,
      "brushCount": 450,
      "note": "（去刷量）"
    },
    {
      "id": "daily-95",
      "name": "少萝电竞店",
      "owner": "谢宇茜",
      "status": "正常",
      "uvPrev": 34,
      "uvToday": 187,
      "consultPrev": 4,
      "consultToday": 2,
      "ordersPrev": 2,
      "ordersToday": 0,
      "newPrev": 0,
      "newToday": 0,
      "brushCount": 450,
      "note": "（去刷量）"
    }
  ],
  "weeklyRows": [
    {
      "id": "weekly-1",
      "name": "酷二狗电竞俱乐部",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 4679,
      "uvW2": 7119,
      "ordersW1": 415,
      "ordersW2": 495,
      "newW1": 102,
      "newW2": 66
    },
    {
      "id": "weekly-2",
      "name": "吞天电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 2507,
      "uvW2": 1283,
      "ordersW1": 359,
      "ordersW2": 249,
      "newW1": 100,
      "newW2": 89
    },
    {
      "id": "weekly-3",
      "name": "EGM背心电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 3161,
      "uvW2": 2259,
      "ordersW1": 59,
      "ordersW2": 50,
      "newW1": 32,
      "newW2": 25
    },
    {
      "id": "weekly-4",
      "name": "追核电竞点单",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 2248,
      "uvW2": 2318,
      "ordersW1": 197,
      "ordersW2": 206,
      "newW1": 102,
      "newW2": 100
    },
    {
      "id": "weekly-5",
      "name": "东东电竞点单",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 10501,
      "uvW2": 11335,
      "ordersW1": 532,
      "ordersW2": 639,
      "newW1": 285,
      "newW2": 312
    },
    {
      "id": "weekly-6",
      "name": "皇帝电竞官号",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 5859,
      "uvW2": 6320,
      "ordersW1": 462,
      "ordersW2": 516,
      "newW1": 197,
      "newW2": 206
    },
    {
      "id": "weekly-7",
      "name": "A7电竞陪玩",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 3431,
      "uvW2": 5833,
      "ordersW1": 8,
      "ordersW2": 78,
      "newW1": 8,
      "newW2": 43
    },
    {
      "id": "weekly-8",
      "name": "小河电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 2276,
      "uvW2": 1436,
      "ordersW1": 63,
      "ordersW2": 53,
      "newW1": 42,
      "newW2": 34
    },
    {
      "id": "weekly-9",
      "name": "星光电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 2687,
      "uvW2": 2293,
      "ordersW1": 168,
      "ordersW2": 147,
      "newW1": 69,
      "newW2": 68
    },
    {
      "id": "weekly-10",
      "name": "得吃电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 1857,
      "uvW2": 2079,
      "ordersW1": 232,
      "ordersW2": 346,
      "newW1": 105,
      "newW2": 158
    },
    {
      "id": "weekly-11",
      "name": "张德帅电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 109,
      "uvW2": 628,
      "ordersW1": 10,
      "ordersW2": 16,
      "newW1": 3,
      "newW2": 8
    },
    {
      "id": "weekly-12",
      "name": "颗秒电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 936,
      "uvW2": 1008,
      "ordersW1": 86,
      "ordersW2": 76,
      "newW1": 23,
      "newW2": 28
    },
    {
      "id": "weekly-13",
      "name": "落川电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 6868,
      "uvW2": 5006,
      "ordersW1": 710,
      "ordersW2": 561,
      "newW1": 313,
      "newW2": 220
    },
    {
      "id": "weekly-14",
      "name": "明星电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 2434,
      "uvW2": 2741,
      "ordersW1": 154,
      "ordersW2": 186,
      "newW1": 72,
      "newW2": 89
    },
    {
      "id": "weekly-15",
      "name": "白鲨电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 866,
      "uvW2": 829,
      "ordersW1": 47,
      "ordersW2": 14,
      "newW1": 37,
      "newW2": 9
    },
    {
      "id": "weekly-16",
      "name": "财神电竞",
      "person": "陈朴",
      "owner": "陈朴",
      "status": "正常",
      "uvW1": 3309,
      "uvW2": 2823,
      "ordersW1": 91,
      "ordersW2": 48,
      "newW1": 19,
      "newW2": 12
    },
    {
      "id": "weekly-17",
      "name": "keg电竞官号",
      "person": "曹子萧",
      "owner": "子潇",
      "status": "正常",
      "uvW1": 1914,
      "uvW2": 12326,
      "ordersW1": 31,
      "ordersW2": 122,
      "newW1": 10,
      "newW2": 51
    },
    {
      "id": "weekly-18",
      "name": "（L类）牛马八宝粥电竞点单",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 9023,
      "uvW2": 8025,
      "ordersW1": 804,
      "ordersW2": 648,
      "newW1": 277,
      "newW2": 243
    },
    {
      "id": "weekly-19",
      "name": "（L类）龙昊电竞俱乐部",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 2359,
      "uvW2": 3662,
      "ordersW1": 55,
      "ordersW2": 106,
      "newW1": 22,
      "newW2": 41
    },
    {
      "id": "weekly-20",
      "name": "（L类）红狗电竞",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 393,
      "uvW2": 323,
      "ordersW1": 53,
      "ordersW2": 44,
      "newW1": 16,
      "newW2": 17
    },
    {
      "id": "weekly-21",
      "name": "（L类）有米电竞点单（旧）",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 3296,
      "uvW2": 3579,
      "ordersW1": 336,
      "ordersW2": 359,
      "newW1": 113,
      "newW2": 101
    },
    {
      "id": "weekly-22",
      "name": "（L类）玩偶电竞点单",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 12216,
      "uvW2": 13328,
      "ordersW1": 1236,
      "ordersW2": 1263,
      "newW1": 586,
      "newW2": 602
    },
    {
      "id": "weekly-23",
      "name": "赫晨电竞",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 1654,
      "uvW2": 2629,
      "ordersW1": 57,
      "ordersW2": 71,
      "newW1": 30,
      "newW2": 32
    },
    {
      "id": "weekly-24",
      "name": "（L类）H4电竞俱乐部",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 2316,
      "uvW2": 2303,
      "ordersW1": 215,
      "ordersW2": 248,
      "newW1": 87,
      "newW2": 94
    },
    {
      "id": "weekly-25",
      "name": "新光电竞",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 2568,
      "uvW2": 1638,
      "ordersW1": 92,
      "ordersW2": 182,
      "newW1": 52,
      "newW2": 75
    },
    {
      "id": "weekly-26",
      "name": "（L类）俭条电竞",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 3642,
      "uvW2": 2975,
      "ordersW1": 153,
      "ordersW2": 190,
      "newW1": 80,
      "newW2": 73
    },
    {
      "id": "weekly-27",
      "name": "（L类）凛冬俱乐部",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 3311,
      "uvW2": 5266,
      "ordersW1": 189,
      "ordersW2": 358,
      "newW1": 108,
      "newW2": 230
    },
    {
      "id": "weekly-28",
      "name": "（L类）天帝俱乐部",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 4332,
      "uvW2": 3794,
      "ordersW1": 212,
      "ordersW2": 166,
      "newW1": 151,
      "newW2": 121
    },
    {
      "id": "weekly-29",
      "name": "（L类）财阀俱乐部",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 618,
      "uvW2": 2350,
      "ordersW1": 32,
      "ordersW2": 114,
      "newW1": 15,
      "newW2": 79
    },
    {
      "id": "weekly-30",
      "name": "怪兽电竞丨(wx88c53f068b624385)",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 13215,
      "uvW2": 9971,
      "ordersW1": 1263,
      "ordersW2": 1106,
      "newW1": 696,
      "newW2": 491
    },
    {
      "id": "weekly-31",
      "name": "大自然电竞",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 1510,
      "uvW2": 2981,
      "ordersW1": 95,
      "ordersW2": 164,
      "newW1": 73,
      "newW2": 130
    },
    {
      "id": "weekly-32",
      "name": "闹特电竞",
      "person": "曹子萧",
      "owner": "曹子萧",
      "status": "正常",
      "uvW1": 628,
      "uvW2": 1337,
      "ordersW1": 19,
      "ordersW2": 72,
      "newW1": 18,
      "newW2": 71
    },
    {
      "id": "weekly-33",
      "name": "稳啦电竞点单",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 2881,
      "uvW2": 1374,
      "ordersW1": 64,
      "ordersW2": 48,
      "newW1": 32,
      "newW2": 21
    },
    {
      "id": "weekly-34",
      "name": "天霸电子竞技陪玩店",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 3773,
      "uvW2": 4181,
      "ordersW1": 406,
      "ordersW2": 420,
      "newW1": 109,
      "newW2": 128
    },
    {
      "id": "weekly-35",
      "name": "初心纯女电竞",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 3302,
      "uvW2": 3711,
      "ordersW1": 165,
      "ordersW2": 194,
      "newW1": 92,
      "newW2": 103
    },
    {
      "id": "weekly-36",
      "name": "麦小龙电竞点单",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 1633,
      "uvW2": 1896,
      "ordersW1": 57,
      "ordersW2": 88,
      "newW1": 28,
      "newW2": 50
    },
    {
      "id": "weekly-37",
      "name": "家长电竞",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 2564,
      "uvW2": 1698,
      "ordersW1": 78,
      "ordersW2": 54,
      "newW1": 41,
      "newW2": 22
    },
    {
      "id": "weekly-38",
      "name": "老飞宇陪玩",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 3951,
      "uvW2": 4494,
      "ordersW1": 17,
      "ordersW2": 29,
      "newW1": 13,
      "newW2": 19
    },
    {
      "id": "weekly-39",
      "name": "立了电竞",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "申诉中",
      "uvW1": 411,
      "uvW2": 84,
      "ordersW1": 11,
      "ordersW2": 0,
      "newW1": 4,
      "newW2": 0
    },
    {
      "id": "weekly-40",
      "name": "老飞宇俱乐部点单",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 593,
      "uvW2": 1631,
      "ordersW1": 35,
      "ordersW2": 74,
      "newW1": 12,
      "newW2": 33
    },
    {
      "id": "weekly-41",
      "name": "战门电竞",
      "person": "姜在东",
      "owner": "姜在东",
      "status": "正常",
      "uvW1": 21,
      "uvW2": 464,
      "ordersW1": 0,
      "ordersW2": 1,
      "newW1": 0,
      "newW2": 1
    },
    {
      "id": "weekly-42",
      "name": "花来商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 3728,
      "uvW2": 3932,
      "ordersW1": 1,
      "ordersW2": 0,
      "newW1": 1,
      "newW2": 0
    },
    {
      "id": "weekly-43",
      "name": "长官商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 10102,
      "uvW2": 10346,
      "ordersW1": 3,
      "ordersW2": 0,
      "newW1": 2,
      "newW2": 0
    },
    {
      "id": "weekly-44",
      "name": "叮当商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 4039,
      "uvW2": 4386,
      "ordersW1": 0,
      "ordersW2": 0,
      "newW1": 0,
      "newW2": 0
    },
    {
      "id": "weekly-45",
      "name": "君扬商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 6329,
      "uvW2": 2391,
      "ordersW1": 1,
      "ordersW2": 0,
      "newW1": 1,
      "newW2": 0
    },
    {
      "id": "weekly-46",
      "name": "H8商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 1227,
      "uvW2": 1229,
      "ordersW1": 39,
      "ordersW2": 4,
      "newW1": 37,
      "newW2": 4
    },
    {
      "id": "weekly-47",
      "name": "牛马号商",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 2018,
      "uvW2": 2642,
      "ordersW1": 0,
      "ordersW2": 0,
      "newW1": 0,
      "newW2": 0
    },
    {
      "id": "weekly-48",
      "name": "小炬商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 1475,
      "uvW2": 1265,
      "ordersW1": 0,
      "ordersW2": 0,
      "newW1": 0,
      "newW2": 0
    },
    {
      "id": "weekly-49",
      "name": "财神商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 1643,
      "uvW2": 1365,
      "ordersW1": 0,
      "ordersW2": 1,
      "newW1": 0,
      "newW2": 1
    },
    {
      "id": "weekly-50",
      "name": "大兵商行",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 0,
      "uvW2": 1808,
      "ordersW1": 0,
      "ordersW2": 0,
      "newW1": 0,
      "newW2": 0
    },
    {
      "id": "weekly-51",
      "name": "猩球电竞俱乐部陪玩",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 3186,
      "uvW2": 1928,
      "ordersW1": 127,
      "ordersW2": 133,
      "newW1": 77,
      "newW2": 59
    },
    {
      "id": "weekly-52",
      "name": "Kasa电竞",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 925,
      "uvW2": 789,
      "ordersW1": 58,
      "ordersW2": 56,
      "newW1": 20,
      "newW2": 14
    },
    {
      "id": "weekly-53",
      "name": "聆音女陪电竞",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 1223,
      "uvW2": 489,
      "ordersW1": 8,
      "ordersW2": 9,
      "newW1": 7,
      "newW2": 8
    },
    {
      "id": "weekly-54",
      "name": "KEG电竞俱乐部点单",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 2806,
      "uvW2": 675,
      "ordersW1": 80,
      "ordersW2": 67,
      "newW1": 44,
      "newW2": 29
    },
    {
      "id": "weekly-55",
      "name": "农场主电竞点单",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 567,
      "uvW2": 481,
      "ordersW1": 29,
      "ordersW2": 16,
      "newW1": 17,
      "newW2": 10
    },
    {
      "id": "weekly-56",
      "name": "农场主电竞三角洲",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 752,
      "uvW2": 1152,
      "ordersW1": 41,
      "ordersW2": 74,
      "newW1": 20,
      "newW2": 31
    },
    {
      "id": "weekly-57",
      "name": "怪兽电竞俱乐部点单",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 57,
      "uvW2": 507,
      "ordersW1": 0,
      "ordersW2": 10,
      "newW1": 0,
      "newW2": 4
    },
    {
      "id": "weekly-58",
      "name": "茶哥电竞",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 0,
      "uvW2": 2253,
      "ordersW1": 0,
      "ordersW2": 30,
      "newW1": 0,
      "newW2": 15
    },
    {
      "id": "weekly-59",
      "name": "星火电竞",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 0,
      "uvW2": 1114,
      "ordersW1": 0,
      "ordersW2": 49,
      "newW1": 0,
      "newW2": 35
    },
    {
      "id": "weekly-60",
      "name": "求真电竞",
      "person": "林诗羽",
      "owner": "林诗羽",
      "status": "正常",
      "uvW1": 0,
      "uvW2": 971,
      "ordersW1": 0,
      "ordersW2": 66,
      "newW1": 0,
      "newW2": 55
    },
    {
      "id": "weekly-61",
      "name": "（L类）二哈电竞点单",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 1738,
      "uvW2": 1661,
      "ordersW1": 56,
      "ordersW2": 83,
      "newW1": 38,
      "newW2": 41
    },
    {
      "id": "weekly-62",
      "name": "ENG俱乐部点单",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 2276,
      "uvW2": 2071,
      "ordersW1": 174,
      "ordersW2": 174,
      "newW1": 70,
      "newW2": 63
    },
    {
      "id": "weekly-63",
      "name": "hanghang电竞",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 421,
      "uvW2": 3593,
      "ordersW1": 33,
      "ordersW2": 30,
      "newW1": 23,
      "newW2": 20
    },
    {
      "id": "weekly-64",
      "name": "小炬电竞",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 3512,
      "uvW2": 2756,
      "ordersW1": 274,
      "ordersW2": 194,
      "newW1": 76,
      "newW2": 51
    },
    {
      "id": "weekly-65",
      "name": "7JIA电子竞技点单",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 2771,
      "uvW2": 1980,
      "ordersW1": 105,
      "ordersW2": 104,
      "newW1": 41,
      "newW2": 40
    },
    {
      "id": "weekly-66",
      "name": "老大电竞",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 4541,
      "uvW2": 4165,
      "ordersW1": 45,
      "ordersW2": 42,
      "newW1": 29,
      "newW2": 24
    },
    {
      "id": "weekly-67",
      "name": "打窝电竞",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "待申诉",
      "uvW1": 1039,
      "uvW2": 362,
      "ordersW1": 4,
      "ordersW2": 0,
      "newW1": 1,
      "newW2": 0
    },
    {
      "id": "weekly-68",
      "name": "KEG电竞点单店",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 8055,
      "uvW2": 7278,
      "ordersW1": 47,
      "ordersW2": 108,
      "newW1": 20,
      "newW2": 77
    },
    {
      "id": "weekly-69",
      "name": "炮炮电竞店官号",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 815,
      "uvW2": 719,
      "ordersW1": 42,
      "ordersW2": 31,
      "newW1": 10,
      "newW2": 9
    },
    {
      "id": "weekly-70",
      "name": "叮当电竞",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 1916,
      "uvW2": 1073,
      "ordersW1": 1,
      "ordersW2": 119,
      "newW1": 0,
      "newW2": 80
    },
    {
      "id": "weekly-71",
      "name": "瓦瓦电竞",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 1444,
      "uvW2": 2813,
      "ordersW1": 66,
      "ordersW2": 62,
      "newW1": 22,
      "newW2": 42
    },
    {
      "id": "weekly-72",
      "name": "海胆电竞点单",
      "person": "贺祖丹",
      "owner": "贺祖丹",
      "status": "正常",
      "uvW1": 3218,
      "uvW2": 2655,
      "ordersW1": 123,
      "ordersW2": 116,
      "newW1": 47,
      "newW2": 48
    },
    {
      "id": "weekly-73",
      "name": "SY电竞点单",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 1234,
      "uvW2": 3830,
      "ordersW1": 21,
      "ordersW2": 51,
      "newW1": 10,
      "newW2": 25
    },
    {
      "id": "weekly-74",
      "name": "少萝电竞店",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 268,
      "uvW2": 5852,
      "ordersW1": 13,
      "ordersW2": 197,
      "newW1": 8,
      "newW2": 177
    },
    {
      "id": "weekly-75",
      "name": "韬略电竞点单",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 0,
      "uvW2": 0,
      "ordersW1": 0,
      "ordersW2": 0,
      "newW1": 0,
      "newW2": 0
    },
    {
      "id": "weekly-76",
      "name": "粑粑电竞护航",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 2742,
      "uvW2": 1711,
      "ordersW1": 35,
      "ordersW2": 24,
      "newW1": 13,
      "newW2": 9
    },
    {
      "id": "weekly-77",
      "name": "Cs电竞护航",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 694,
      "uvW2": 707,
      "ordersW1": 28,
      "ordersW2": 28,
      "newW1": 9,
      "newW2": 6
    },
    {
      "id": "weekly-78",
      "name": "胜海电竞俱乐部",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 2216,
      "uvW2": 4233,
      "ordersW1": 28,
      "ordersW2": 54,
      "newW1": 10,
      "newW2": 39
    },
    {
      "id": "weekly-79",
      "name": "拔牙电竞俱乐部",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 1560,
      "uvW2": 678,
      "ordersW1": 33,
      "ordersW2": 17,
      "newW1": 22,
      "newW2": 11
    },
    {
      "id": "weekly-80",
      "name": "小里的电竞点单",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 1228,
      "uvW2": 955,
      "ordersW1": 80,
      "ordersW2": 110,
      "newW1": 21,
      "newW2": 25
    },
    {
      "id": "weekly-81",
      "name": "带富电竞点单",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 608,
      "uvW2": 720,
      "ordersW1": 23,
      "ordersW2": 15,
      "newW1": 10,
      "newW2": 2
    },
    {
      "id": "weekly-82",
      "name": "KEG电竞护航店",
      "person": "谢宇茜",
      "owner": "谢宇茜",
      "status": "正常",
      "uvW1": 423,
      "uvW2": 1657,
      "ordersW1": 158,
      "ordersW2": 344,
      "newW1": 76,
      "newW2": 133
    }
  ]
};
